// tokens.h
#define CONST       1
#define VAR         2
#define PROC        3
#define CALL        4
#define TK_BEGIN    5
#define END         6
#define IF          7
#define THEN        8
#define ELSE        9
#define WHILE       10
#define DO          11
#define READ        12
#define PRINT       13
#define DIVISIBLE   14
#define BY          15
#define EQ          16
#define NEQ         17
#define LT          18
#define LEQ         19
#define GT          20
#define GEQ         21
#define PLUS        22
#define MINUS       23
#define MULT        24
#define DIV         25
#define DOT         26
#define SEMICOLON   27
#define ASSIGN      28
#define ASSIGNOP    29
#define COMMA       30
#define LPAREN      31
#define RPAREN      32
#define IDENT       33
#define NUMBER      34
